"""Jinja2 environment with custom filters and globals."""

from __future__ import annotations

from pathlib import Path
from urllib.parse import quote

import markdown as _markdown
from fastapi.templating import Jinja2Templates
from markupsafe import Markup, escape

TEMPLATE_DIR = Path(__file__).parent / "templates"
templates = Jinja2Templates(directory=str(TEMPLATE_DIR))


def _md(text: str) -> Markup:
    if not text:
        return Markup("")
    html = _markdown.markdown(
        text, extensions=["fenced_code", "tables", "nl2br"]
    )
    return Markup(html)


def _truncatechars(text: str | None, n: int) -> str:
    if not text:
        return ""
    if len(text) <= n:
        return text
    return text[: max(0, n - 1)] + "…"


def _datetimefmt(value, fmt: str = "%Y-%m-%d %H:%M") -> str:
    if value is None:
        return ""
    try:
        return value.strftime(fmt)
    except AttributeError:
        return str(value)


def _pluralize(value, suffix: str = "s") -> str:
    try:
        n = len(value)
    except TypeError:
        try:
            n = int(value)
        except (TypeError, ValueError):
            return ""
    return "" if n == 1 else suffix


def github_issue_url(finding, audit_run) -> str:
    if not audit_run or not audit_run.github_repo_url:
        return ""
    base = audit_run.github_repo_url.rstrip("/")
    title = f"[{finding.severity}] {finding.title or finding.rule_id}"
    body = f"## {finding.title or finding.rule_id}\n\n"
    body += f"**Severity:** {finding.severity} | **Difficulty:** {finding.difficulty}\n"
    body += f"**Scenario:** {finding.scenario_id}\n\n"
    body += f"### Description\n\n{finding.description}\n\n"
    body += f"### Impact\n\n{finding.impact}\n\n"
    body += f"### Recommendations\n\n{finding.recommendations}\n"
    locs = finding.locations
    if locs:
        body += "\n### Locations\n\n"
        for loc in locs:
            url = audit_run.github_file_url(loc.file_path, loc.start_line)
            if url:
                body += f"- [{loc.file_path}:{loc.start_line}]({url})\n"
            else:
                body += f"- {loc.file_path}:{loc.start_line}\n"
    body += "\n---\n*Generated by llmpuffin*"
    return f"{base}/issues/new?title={quote(title)}&body={quote(body)}"


def location_link(loc, audit_run=None) -> Markup:
    display = f"{loc.file_path}:{loc.start_line}"
    if audit_run and audit_run.github_repo_url:
        url = audit_run.github_file_url(loc.file_path, loc.start_line)
        if url:
            return Markup(
                f'<a href="{escape(url)}" target="_blank">{escape(display)}</a>'
            )
    return Markup(escape(display))


templates.env.filters["md"] = _md
templates.env.filters["truncatechars"] = _truncatechars
templates.env.filters["datetimefmt"] = _datetimefmt
templates.env.filters["pluralize"] = _pluralize
templates.env.globals["github_issue_url"] = github_issue_url
templates.env.globals["location_link"] = location_link
