runtime = "podman"
#runtime = "nexecutor"
#runtime = "microvm"
#microvm_image_arn = "arn:aws:lambda:us-east-1:211360623297:microvm-image:llmpuffin1"
#microvm_region = "us-east-1"
#microvm_profile = "admin-executor"

[postgres]
url = "postgresql://localhost:5434/llmpuffin"

[web]
port = 8000
debug = true
secret_key = "dev-insecure-key-change-in-prod"
allowed_hosts = ["*"]

[github]
app_id = "3779149"
installation_id = "133980810"
findings_repo = "KittyCAD/cvd-internal"

[auth]
enabled = true
provider_url = "http://localhost:9090"
client_id = "llmpuffin"
client_secret = "dev-oidc-secret-not-for-production"

[logging]
level = "INFO"
