#runtime = "podman"
runtime = "nexecutor"
#runtime = "microvm"

[postgres]
url = "postgresql://localhost:5434/llmpuffin"

[web]
port = 8000
debug = true
secret_key = "dev-insecure-key-change-in-prod"
allowed_hosts = ["*"]
base_url = "http://127.0.0.1:8000/"

[github]
app_id = "3779149"
installation_id = "133980810"
findings_repo = "KittyCAD/cvd-internal"

[auth]
enabled = true
provider_url = "http://localhost:9090"
client_id = "llmpuffin"
client_secret = "dev-oidc-secret-not-for-production"

[logging]
level = "INFO"
