"""Finding routes."""

from __future__ import annotations

import logging
from pathlib import Path
from typing import Annotated
from urllib.parse import quote

from fastapi import APIRouter, Depends, Form, HTTPException, Request
from fastapi.responses import HTMLResponse, RedirectResponse
from sqlalchemy import select, update as sa_update
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy.orm import selectinload

from llmpuffin.agent import fork_audit
from llmpuffin.config import Config, Profile
from llmpuffin.db import async_session
from llmpuffin.harness import HarnessConfig
from llmpuffin.models import AuditRun, AuditThread, Finding

from llmpuffin_fastapi.deps import get_db, spawn_audit
from llmpuffin_fastapi.github import create_issue
from llmpuffin_fastapi.templates_env import templates

log = logging.getLogger("llmpuffin")
router = APIRouter()


async def _get_finding(db: AsyncSession, finding_id: int) -> Finding | None:
    return (
        await db.execute(
            select(Finding)
            .options(
                selectinload(Finding.audit_run).selectinload(AuditRun.profile),
                selectinload(Finding.locations),
            )
            .where(Finding.id == finding_id)
        )
    ).scalar_one_or_none()


@router.get("/findings/{finding_id}/", response_class=HTMLResponse)
async def finding_detail(
    finding_id: int,
    request: Request,
    db: Annotated[AsyncSession, Depends(get_db)],
    success: str | None = None,
    error: str | None = None,
):
    gh_config = Config.load().github
    finding = await _get_finding(db, finding_id)
    if finding is None:
        raise HTTPException(status_code=404)
    return templates.TemplateResponse(
        request,
        "finding_detail.html",
        {
            "finding": finding,
            "audit_run": finding.audit_run,
            "github_configured": gh_config.configured
            and bool(finding.audit_run.github_repo_url),
            "locations": finding.locations,
            "success": success,
            "error": error,
        },
    )


@router.post("/findings/{finding_id}/issue/")
async def finding_create_issue(
    finding_id: int, db: Annotated[AsyncSession, Depends(get_db)]
):
    finding = await _get_finding(db, finding_id)
    if finding is None:
        raise HTTPException(status_code=404)
    audit_run = finding.audit_run
    gh_config = Config.load().github

    if not gh_config.configured or not audit_run.github_repo_url:
        return RedirectResponse(
            f"/findings/{finding_id}/?error={quote('GitHub App not configured')}",
            status_code=303,
        )

    repo = audit_run.github_repo_url.rstrip("/").removeprefix("https://github.com/")
    title = f"[{finding.severity}] {finding.title or finding.rule_id}"
    body = f"## {finding.title or finding.rule_id}\n\n"
    body += f"**Severity:** {finding.severity} | **Difficulty:** {finding.difficulty}\n"
    body += f"**Scenario:** {finding.scenario_id}\n\n"
    body += f"### Description\n\n{finding.description}\n\n"
    body += f"### Impact\n\n{finding.impact}\n\n"
    body += f"### Recommendations\n\n{finding.recommendations}\n"
    if finding.locations:
        body += "\n### Locations\n\n"
        for loc in finding.locations:
            url = audit_run.github_file_url(loc.file_path, loc.start_line)
            if url:
                body += f"- [{loc.file_path}:{loc.start_line}]({url})\n"
            else:
                body += f"- {loc.file_path}:{loc.start_line}\n"
    body += "\n---\n*Generated by llmpuffin*"

    try:
        private_key = Path(gh_config.private_key_path).read_text()
        issue_url = create_issue(
            repo=repo,
            title=title,
            body=body,
            app_id=gh_config.app_id,
            private_key=private_key,
            installation_id=gh_config.installation_id,
            labels=["security", finding.severity],
        )
        return RedirectResponse(
            f"/findings/{finding_id}/?success={quote(f'Issue created: {issue_url}')}",
            status_code=303,
        )
    except Exception as exc:
        log.exception("Failed to create GitHub issue")
        return RedirectResponse(
            f"/findings/{finding_id}/?error={quote(f'Failed to create issue: {exc}')}",
            status_code=303,
        )


@router.post("/findings/{finding_id}/fork/")
async def finding_fork(
    finding_id: int,
    db: Annotated[AsyncSession, Depends(get_db)],
    message: Annotated[str, Form()] = "",
):
    finding = await _get_finding(db, finding_id)
    if finding is None:
        raise HTTPException(status_code=404)
    run = finding.audit_run

    if not finding.thread_id:
        return RedirectResponse(
            f"/findings/{finding_id}/?error={quote('Finding has no originating thread')}",
            status_code=303,
        )

    source_thread = (
        await db.execute(
            select(AuditThread).where(AuditThread.thread_id == finding.thread_id)
        )
    ).scalar_one_or_none()
    if source_thread and source_thread.status == "running":
        return RedirectResponse(
            f"/findings/{finding_id}/?error={quote('Source thread is still running, cannot fork')}",
            status_code=303,
        )

    toml_str = run.profile_toml or (run.profile.profile_toml if run.profile else "")
    if not toml_str:
        return RedirectResponse(
            f"/findings/{finding_id}/?error={quote('No config available for fork')}",
            status_code=303,
        )

    finding_context = (
        f"This conversation is forked to investigate finding #{finding.local_id}.\n"
        f"Title: {finding.title}\n"
        f"Scenario: {finding.scenario_id}\n"
        f"Severity: {finding.severity} | Difficulty: {finding.difficulty}\n"
        f"Description: {finding.description[:500]}\n\n"
    )
    user_input = message.strip()
    user_message = finding_context + (
        user_input or "Investigate this finding further. Try to validate or refute it."
    )

    async def _do_fork():
        profile = Profile.from_toml_string(toml_str)
        harness_config = HarnessConfig(profile=profile, profile_toml=toml_str)
        try:
            result = await fork_audit(
                harness_config,
                source_thread_id=finding.thread_id,
                user_message=user_message,
            )
        except Exception:
            log.exception("Background finding fork failed")
            return
        if result.thread_id:
            async with async_session() as s:
                await s.execute(
                    sa_update(Finding)
                    .where(Finding.id == finding_id)
                    .values(fork_thread_id=result.thread_id)
                )
                await s.commit()

    spawn_audit(_do_fork())
    return RedirectResponse(
        f"/findings/{finding_id}/?success={quote('Fork started')}", status_code=303
    )
