# Generated by Django 6.0.5 on 2026-05-15 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llmpuffin", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="deleted",
            field=models.BooleanField(default=False),
        ),
    ]
