# Generated by Django 6.0.5 on 2026-05-15 14:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llmpuffin", "0002_finding_deleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrun",
            name="git_commit",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="auditrun",
            name="git_remote",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
        migrations.AddField(
            model_name="auditrun",
            name="github_repo_url",
            field=models.CharField(blank=True, default="", max_length=512),
        ),
    ]
