# Generated by Django 6.0.5 on 2026-05-15 15:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("llmpuffin", "0003_auditrun_git_commit_auditrun_git_remote_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="auditrun",
            name="git_remote",
        ),
    ]
