# Generated by Django 6.0.5 on 2026-05-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llmpuffin", "0003_remove_auditrun_thread_id_auditthread"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditrun",
            name="config_toml",
            field=models.TextField(blank=True, default=""),
        ),
    ]
