# Generated by Django 6.0.5 on 2026-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llmpuffin", "0004_remove_auditrun_git_remote"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="fork_thread_id",
            field=models.CharField(
                blank=True, db_index=True, default="", max_length=64
            ),
        ),
    ]
