# Generated by Django 6.0.5 on 2026-05-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llmpuffin", "0006_remove_auditrun_error_remove_auditrun_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="finding",
            name="local_id",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="auditthread",
            name="status",
            field=models.CharField(default="running", max_length=32),
        ),
    ]
