# Generated by Django 6.0.5 on 2026-05-18 14:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("llmpuffin", "0008_backfill_finding_local_ids"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditthread",
            name="container_id",
            field=models.CharField(blank=True, default="", max_length=128),
        ),
    ]
