"""Template tags and filters for finding display."""

from urllib.parse import quote

import markdown as _markdown
from django import template
from django.utils.html import escape
from django.utils.safestring import mark_safe

register = template.Library()


# FIXME: This preserves finding details in the browser history
@register.simple_tag
def github_issue_url(finding, audit_run) -> str:
    """Build a GitHub new-issue URL pre-filled with finding details."""
    if not audit_run or not audit_run.github_repo_url:
        return ""
    base = audit_run.github_repo_url.rstrip("/")
    title = f"[{finding.severity}] {finding.title or finding.rule_id}"
    body = f"## {finding.title or finding.rule_id}\n\n"
    body += f"**Severity:** {finding.severity} | **Difficulty:** {finding.difficulty}\n"
    body += f"**Scenario:** {finding.scenario_id}\n\n"
    body += f"### Description\n\n{finding.description}\n\n"
    body += f"### Impact\n\n{finding.impact}\n\n"
    body += f"### Recommendations\n\n{finding.recommendations}\n"
    locs = finding.locations.all()
    if locs:
        body += "\n### Locations\n\n"
        for loc in locs:
            url = audit_run.github_file_url(loc.file_path, loc.start_line)
            if url:
                body += f"- [{loc.file_path}:{loc.start_line}]({url})\n"
            else:
                body += f"- {loc.file_path}:{loc.start_line}\n"
    body += "\n---\n*Generated by llmpuffin*"
    return f"{base}/issues/new?title={quote(title)}&body={quote(body)}"


@register.filter(name="md")
def render_markdown(text: str) -> str:
    """Render markdown text to HTML."""
    if not text:
        return ""
    html = _markdown.markdown(
        text,
        extensions=["fenced_code", "tables", "nl2br"],
    )
    return mark_safe(html)


@register.simple_tag
def location_link(loc, audit_run=None) -> str:
    """Render a FindingLocation as a GitHub link or plain text.

    Uses the structured file_path and start_line from the database directly.
    """
    display = f"{loc.file_path}:{loc.start_line}"
    if audit_run and audit_run.github_repo_url:
        url = audit_run.github_file_url(loc.file_path, loc.start_line)
        if url:
            return mark_safe(
                f'<a href="{escape(url)}" target="_blank">{escape(display)}</a>'
            )
    return escape(display)
