"""GitHub reporting service for findings.

Handles creating/updating GitHub issues and security advisories for findings,
including the GitHubLink persistence.
"""

from __future__ import annotations

import logging
from dataclasses import dataclass

from llmpuffin.db import DB
from llmpuffin.github import GitHubClient
from llmpuffin.models import Finding, GitHubLink

log = logging.getLogger("llmpuffin")


@dataclass
class ReportResult:
    """Result of a GitHub report operation."""

    success: bool
    message: str


def _repo_from_github_url(url: str) -> str | None:
    """Extract 'owner/repo' from a GitHub URL."""
    url = url.rstrip("/")
    if "github.com/" not in url:
        return None
    parts = url.split("github.com/", 1)[1].split("/")
    if len(parts) >= 2:
        return f"{parts[0]}/{parts[1]}"
    return None


def _build_finding_body(finding: Finding, base_url: str = "") -> str:
    """Build the markdown body for a GitHub issue/advisory."""
    body = (
        f"**Severity:** {finding.severity} | **Difficulty:** {finding.difficulty}\n\n"
    )
    body += f"## Description\n\n{finding.description}\n\n"
    body += f"## Exploit Scenario\n\n{finding.exploit_scenario}\n\n"
    body += f"## Recommendations\n\n{finding.recommendations}\n"
    if finding.locations:
        body += "\n## Locations\n\n"
        for loc in finding.locations:
            url = loc.github_url()
            if url:
                body += f"{url}\n\n"
            else:
                body += f"- {loc.file_path}:{loc.start_line}\n\n"
    if base_url:
        body += f"\n---\n*Generated by [llmpuffin]({base_url}/findings/{finding.id}/)*"
    else:
        body += "\n---\n*Generated by llmpuffin*"
    return body


async def report_finding_to_github(
    finding: Finding,
    *,
    gh: GitHubClient,
    db: DB,
    base_url: str = "",
) -> ReportResult:
    """Create or update a GitHub issue/advisory for a finding.

    Logic:
      - If a GitHubLink already exists, update the existing issue/advisory.
      - Public repos + findings_repo → issue in the private findings repo.
      - Public repos (no findings_repo) → draft security advisory.
      - Private repos → GitHub issue in the source repo.
    """
    audit_run = finding.audit_run
    if not audit_run or not audit_run.github_repo_url:
        return ReportResult(False, "No GitHub repo URL on audit run")
    if not finding.title:
        return ReportResult(False, "Title is required")

    repo = audit_run.github_repo_url.rstrip("/").removeprefix("https://github.com/")
    repo_info = gh.check_repo_access(repo)
    if repo_info is None:
        return ReportResult(False, "Cannot access repo — is the GitHub App installed?")

    is_private = repo_info.get("private", False)
    title = finding.title
    body = _build_finding_body(finding, base_url)

    # Update existing issue/advisory.
    if finding.github_link:
        return _update_existing(
            finding, gh, repo, title, body, audit_run.github_repo_url
        )

    # Create new.
    if not is_private and gh.findings_repo:
        return await _create_in_findings_repo(
            finding, gh, db, repo, title, body, audit_run.github_repo_url
        )
    if not is_private:
        return await _create_advisory(finding, gh, db, repo, title, body)
    return await _create_issue(finding, gh, db, repo, title, body)


def _update_existing(
    finding: Finding,
    gh: GitHubClient,
    repo: str,
    title: str,
    body: str,
    github_repo_url: str,
) -> ReportResult:
    link = finding.github_link
    assert link is not None
    link_repo = _repo_from_github_url(link.github_url) or repo
    update_body = body
    if link_repo != repo:
        update_body = f"**Source repo:** {github_repo_url}\n\n{body}"

    if link.github_type == "issue":
        issue_state = (
            "closed" if finding.status in ("fixed", "invalid", "deleted") else "open"
        )
        try:
            gh.update_issue(
                repo=link_repo,
                issue_number=int(link.github_id),
                title=title,
                body=update_body,
                state=issue_state,
            )
            return ReportResult(True, "Issue updated")
        except Exception as exc:
            log.exception("Failed to update GitHub issue")
            return ReportResult(False, f"Failed to update: {exc}")
    else:
        if finding.status != "open":
            log.warning(
                "Finding %d has status '%s' but advisory state sync is not supported — "
                "advisory %s must be managed manually on GitHub",
                finding.id,
                finding.status,
                link.github_id,
            )
        try:
            gh.update_advisory(
                repo=link_repo,
                ghsa_id=link.github_id,
                summary=title,
                description=body,
                severity=finding.severity,
            )
            return ReportResult(True, "Advisory updated")
        except Exception as exc:
            log.exception("Failed to update GitHub advisory")
            return ReportResult(False, f"Failed to update: {exc}")


async def _create_in_findings_repo(
    finding: Finding,
    gh: GitHubClient,
    db: DB,
    repo: str,
    title: str,
    body: str,
    github_repo_url: str,
) -> ReportResult:
    findings_repo_info = gh.check_repo_access(gh.findings_repo)
    if findings_repo_info is None:
        return ReportResult(
            False,
            f"Cannot access issues repo '{gh.findings_repo}' — is the GitHub App installed?",
        )
    if not findings_repo_info.get("private", False):
        return ReportResult(
            False,
            f"Issues repo '{gh.findings_repo}' is not private — refusing to post findings to a public repo",
        )
    try:
        issue_url = gh.create_issue(
            repo=gh.findings_repo,
            title=title,
            body=f"**Source repo:** {github_repo_url}\n\n{body}",
            labels=["vulnerability"],
        )
        issue_number = issue_url.rstrip("/").rsplit("/", 1)[-1]
        async with db.async_session() as s:
            s.add(
                GitHubLink(
                    finding_id=finding.id,
                    github_type="issue",
                    github_id=issue_number,
                    github_url=issue_url,
                )
            )
            await s.commit()
        return ReportResult(True, f"Issue created in {gh.findings_repo}")
    except Exception as exc:
        log.exception("Failed to create issue in findings_repo")
        return ReportResult(False, f"Failed to create issue: {exc}")


async def _create_advisory(
    finding: Finding,
    gh: GitHubClient,
    db: DB,
    repo: str,
    title: str,
    body: str,
) -> ReportResult:
    try:
        advisory_url = gh.create_draft_advisory(
            repo=repo,
            summary=title,
            description=body,
            severity=finding.severity,
        )
        ghsa_id = advisory_url.rstrip("/").rsplit("/", 1)[-1]
        async with db.async_session() as s:
            s.add(
                GitHubLink(
                    finding_id=finding.id,
                    github_type="advisory",
                    github_id=ghsa_id,
                    github_url=advisory_url,
                )
            )
            await s.commit()
        return ReportResult(True, "Draft security advisory created")
    except Exception as exc:
        log.exception("Failed to create advisory")
        return ReportResult(False, f"Failed to create advisory: {exc}")


async def _create_issue(
    finding: Finding,
    gh: GitHubClient,
    db: DB,
    repo: str,
    title: str,
    body: str,
) -> ReportResult:
    try:
        issue_url = gh.create_issue(
            repo=repo,
            title=title,
            body=body,
            labels=["vulnerability"],
        )
        issue_number = issue_url.rstrip("/").rsplit("/", 1)[-1]
        async with db.async_session() as s:
            s.add(
                GitHubLink(
                    finding_id=finding.id,
                    github_type="issue",
                    github_id=issue_number,
                    github_url=issue_url,
                )
            )
            await s.commit()
        return ReportResult(True, "Issue created")
    except Exception as exc:
        log.exception("Failed to create GitHub issue")
        return ReportResult(False, f"Failed to create issue: {exc}")
