name: docker-image
permissions:
  packages: write
  contents: read
on:
  pull_request:
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock
      - Dockerfile
      - .github/workflows/docker-image.yml
  push:
    branches:
      - main
    paths:
      - '**.py'
      - pyproject.toml
      - uv.lock
      - Dockerfile
      - .github/workflows/docker-image.yml
  workflow_dispatch:
concurrency:
  group: docker-image-${{ github.ref }}
  cancel-in-progress: false
jobs:
  docker-image:
    runs-on:
      - runs-on=${{ github.run_id }}
      - runner=8cpu-linux-x64
    steps:
      - uses: actions/checkout@v4
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up env vars
        shell: bash
        run: |
          maybe_branch=${GITHUB_HEAD_REF//\//-}
          BRANCH=${maybe_branch:-main}
          echo "BRANCH=${BRANCH}" >> "$GITHUB_ENV"
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          CACHE_REPO: ghcr.io/${{ github.repository }}:buildcache
        with:
          context: .
          push: true
          file: ./Dockerfile
          tags: |
            ghcr.io/${{ github.repository }}:${{ env.BRANCH }}
            ghcr.io/${{ github.repository }}:${{ github.sha }}
          cache-from: type=registry,ref=${{ env.CACHE_REPO }}
          cache-to: type=registry,ref=${{ env.CACHE_REPO }},mode=min,compression=zstd,compression-level=22
